#!/usr/bin/python

from __future__ import print_function

import argparse
import json
import inspect
import pprint
import socket
import sys

from elasticsearch import Elasticsearch
from elasticsearch.client.utils import NamespacedClient

__author__ = 'Aleksey Chudov <aleksey.chudov@gmail.com>'
__date__ = '8 Dec 2016'
__version__ = '1.0.2'

USAGE = """usage examples:
    elastic --help

    elastic localhost:9200 /
    elastic localhost:9200 /discovery
    elastic localhost:9200 /discovery/cluster
    elastic localhost:9200 /discovery/nodes
    elastic localhost:9200 /cat
    elastic localhost:9200 /cat/master
    elastic localhost:9200 /cluster
    elastic localhost:9200 /cluster/health
    elastic localhost:9200 /cluster/health/status
    elastic localhost:9200 /cluster/health/status -d
    elastic localhost:9200 /cluster/health/status level=shards -d

    elastic localhost:9200,localhost:9201,localhost:9202 /
"""

ES_DEFAULT_RETRIES = 1
ES_DEFAULT_TIMEOUT = 3


class ElasticZBX(object):

    ERROR_VALUE = 'ZBX_NOTSUPPORTED'

    def __init__(self, args):
        self.args = args
        self.es = Elasticsearch(args.nodes, timeout=args.timeout,
                                retry_on_timeout=True, max_retries=args.retries)

    def __call__(self):
        if self._is_discovery():
            result = self._get_discovery()
        else:
            objects, attributes = self._parse_paths()
            if self.args.debug:
                debug('objects', objects)
                debug('attributes', attributes)
            result = self._get_value(objects, attributes)

        return result

    def _get_discovery(self, method_prefix='_discovery_'):
        result = []
        method_name = method_prefix + self.args.paths[-1]
        if self._is_discovery_root():
            result.extend(get_startswith_strip(self, is_method, method_prefix))
        elif hasattr(self, method_name):
            discovery = {'data': getattr(self, method_name)()}
            result.append(json.dumps(discovery, separators=(',', ':')))
        else:
            result.append(self.ERROR_VALUE)

        return join_string(result)

    def _discovery_cluster(self, metric='cluster_name'):
        cluster_state = self.es.cluster.state(metric)
        if self.args.debug:
            debug_name = '{}(metric={})'.format(self.es.cluster.state, metric)
            debug(debug_name, cluster_state)
        data = []
        if self._is_node_match():
            data.append({'{#ES_CLUSTER_NAME}': cluster_state[metric]})

        return data

    def _discovery_nodes(self, metric='process'):
        nodes_info = self.es.nodes.info(metric)
        if self.args.debug:
            debug_name = '{}(metric={})'.format(self.es.nodes.info, metric)
            debug(debug_name, nodes_info)
        data = []
        for node_id in nodes_info['nodes'].keys():
            node_name = nodes_info['nodes'][node_id]['name']
            if self._is_node_match(node_name):
                item = {
                    '{#ES_CLUSTER_NAME}': nodes_info['cluster_name'],
                    '{#ES_NODE_ID}': node_id,
                    '{#ES_NODE_NAME}': node_name
                }
                data.append(item)

        return data

    def _is_discovery(self):
        return len(self.args.paths) and self.args.paths[0] == 'discovery'

    def _is_discovery_root(self):
        return len(self.args.paths) == 1 and self.args.paths[0] == 'discovery'

    def _is_node_match(self, name='', match=True):
        node = self.args.params.get('node')
        if node == 'local' and name:
            match = (name == socket.gethostname() or name == socket.getfqdn())
        elif node:
            match = (node == socket.gethostname() or node == socket.getfqdn())

        return match

    def _parse_paths(self):
        attributes = []
        objects = [self.es]
        for i in range(len(self.args.paths)):
            path = self.args.paths[i]
            if hasattr(objects[-1], path):
                objects.append(getattr(objects[-1], path))
            else:
                attributes.extend(self.args.paths[i:])
                break

        return objects, attributes

    def _get_value(self, objects, attributes):
        obj = objects[-1]
        values = []

        if is_es(obj) and not attributes:
            values.append('discovery')
            values.extend(get_public_members(obj, is_client))
            values.extend(get_public_members(obj, is_method))

        elif is_client(obj) and not attributes:
            values.extend(get_public_members(obj, is_method))

        elif is_method(obj):
            result = obj(**self.args.params)
            if self.args.debug:
                debug_name = '{}({})'.format(obj, join_params(self.args.params))
                debug(debug_name, result)

            values.extend(self._get_attributes(result, attributes))
        else:
            values.append(self.ERROR_VALUE)

        return join_string(values)

    def _get_attributes(self, obj, attributes):
        results = []
        try:
            for attr in attributes:
                if attr == attributes[-1] and is_list(obj):
                    for obj_elem in obj:
                        results.append(obj_elem[attr])
                else:
                    obj = obj[attr]
        except (KeyError, TypeError):
            results.append(self.ERROR_VALUE)

        if not results:
            if is_dict(obj):
                results.extend(obj.keys())
            elif is_list(obj):
                results.extend(obj)
            else:
                results.append(obj)

        return results


def debug(name, value):
    print('{}: '.format(name), file=sys.stderr)
    pprint.pprint(value, stream=sys.stderr)


def get_startswith_strip(obj, predicate, prefix):
    names = []
    for name, value in inspect.getmembers(obj, predicate):
        if name.startswith(prefix):
            end_of_prefix = len(prefix)
            names.append(name[end_of_prefix:])

    return names


def get_public_members(obj, predicate):
    names = []
    for name, values in inspect.getmembers(obj, predicate):
        if not name.startswith('_'):
            names.append(name)

    return names


def is_client(obj):
    return isinstance(obj, NamespacedClient)


def is_dict(obj):
    return isinstance(obj, dict)


def is_es(obj):
    return isinstance(obj, Elasticsearch)


def is_list(obj):
    return isinstance(obj, list)


def is_method(obj):
    return inspect.ismethod(obj)


def join_params(params):
    return ', '.join('{}={}'.format(*item) for item in params.items())


def join_string(iterable, function=None):
    return ' '.join(filter(function, map(str, iterable))).strip()


def split_params(param, sep=None):
    return dict(p.split(sep) for p in param if len(p.split(sep)) == 2)


def split_string(string, sep=None, function=None):
    return filter(function, string.split(sep))


def parse_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter, epilog=USAGE)

    parser.add_argument('-d', '--debug', action='store_true')
    parser.add_argument('-r', '--retries', default=ES_DEFAULT_RETRIES, type=int)
    parser.add_argument('-t', '--timeout', default=ES_DEFAULT_TIMEOUT, type=int)
    parser.add_argument('node')
    parser.add_argument('path')
    parser.add_argument('param', nargs='*')

    args = parser.parse_args()
    args.nodes = split_string(args.node, ',')
    args.paths = split_string(args.path, '/')
    args.params = split_params(args.param, '=')
    args.zabbix_get = ElasticZBX(args)

    if args.debug:
        debug('args', args)

    return args


def main():
    args = parse_args()
    try:
        print(args.zabbix_get())
    except Exception as e:
        if args.debug:
            raise
        print(e)


if __name__ == '__main__':
    main()
