#!/usr/bin/python

import argparse
import json

__author__ = 'Aleksey Chudov <aleksey.chudov@gmail.com>'
__date__ = '7 Nov 2016'
__version__ = '1.0.4'


class DiskStats(object):

    DISKSTATS = '/proc/diskstats'

    @classmethod
    def discovery(cls, args):
        discovery = {'data': []}
        try:
            data = []
            with open(cls.DISKSTATS, 'r') as diskstats:
                for line in diskstats.readlines():
                    columns = line.split()
                    if len(columns) != 14 or columns[3] == columns[4] == '0':
                        continue
                    item = {'{#DISK_MAJOR}': columns[0],
                            '{#DISK_MINOR}': columns[1],
                            '{#DISK_NAME}': columns[2]}
                    data.append(item)
            discovery['data'] = data
        except Exception:
            if args.debug:
                raise
        return json.dumps(discovery, separators=(',', ':'))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true')
    parser.set_defaults(func=DiskStats.discovery)
    return parser.parse_args()


def main():
    args = parse_args()
    try:
        print(args.func(args))
    except Exception as e:
        if args.debug:
            raise
        print(e)


if __name__ == '__main__':
    main()
